language: python
python:
    - "3.5"
    - "3.6"
env:
    - DJANGO_PACKAGE="Django>=1.10,<1.11"
    - DJANGO_PACKAGE="Django==1.11"
install: pip install $DJANGO_PACKAGE
script: PYTHONPATH=. DJANGO_SETTINGS_MODULE=bridgekeeper.tests.settings django-admin test
